/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ListPagination {
        /**
          * The count of all items in the list.
         */
        "count": number;
        /**
          * How many items per page shall be shown on the list?
         */
        "itemsPerPage": number;
        /**
          * The current offset of the list.
         */
        "offset": number;
    }
    interface VehicleList {
        /**
          * The title of this Vehicle List.
         */
        "listTitle": string;
    }
}
declare global {
    interface HTMLListPaginationElement extends Components.ListPagination, HTMLStencilElement {
    }
    var HTMLListPaginationElement: {
        prototype: HTMLListPaginationElement;
        new (): HTMLListPaginationElement;
    };
    interface HTMLVehicleListElement extends Components.VehicleList, HTMLStencilElement {
    }
    var HTMLVehicleListElement: {
        prototype: HTMLVehicleListElement;
        new (): HTMLVehicleListElement;
    };
    interface HTMLElementTagNameMap {
        "list-pagination": HTMLListPaginationElement;
        "vehicle-list": HTMLVehicleListElement;
    }
}
declare namespace LocalJSX {
    interface ListPagination {
        /**
          * The count of all items in the list.
         */
        "count"?: number;
        /**
          * How many items per page shall be shown on the list?
         */
        "itemsPerPage"?: number;
        /**
          * The current offset of the list.
         */
        "offset"?: number;
        /**
          * Emits, when a paging is triggered.
         */
        "onPaging"?: (event: CustomEvent<{ offset: number }>) => void;
    }
    interface VehicleList {
        /**
          * The title of this Vehicle List.
         */
        "listTitle"?: string;
    }
    interface IntrinsicElements {
        "list-pagination": ListPagination;
        "vehicle-list": VehicleList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "list-pagination": LocalJSX.ListPagination & JSXBase.HTMLAttributes<HTMLListPaginationElement>;
            "vehicle-list": LocalJSX.VehicleList & JSXBase.HTMLAttributes<HTMLVehicleListElement>;
        }
    }
}
